### ISSUE TITLE
[Request] Windows Batch file setup

### ISSUE THREAD

**Issue by NEXUS2345** [Robotia/WarmRoastSetup#1]
Would it be possible for you to create a batch file that allows us to setup WarmRoast on Windows machines using this repo?

**Comment by sameer** [comment]
I have yet to figure out how batch really works, but I will see what I can do. :stuck_out_tongue:

**Comment by sameer** [comment]
@NEXUS2345 Pester me on Discord, I'll get around to it.

**Comment by sameer** [comment]
Fulfilled.
